---
title: "Explore dog breeding dataset"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5)
#load data wrangling packages
library(data.table)
library(tidyverse)
library(lubridate)
library(tidytuesdayR)

#load path setting package
library(here)

#load tidymodels package
library(tidymodels)
```

```{r get_data}
tuesdata <- tidytuesdayR::tt_load(2022, week = 5)
# OR can use with date
# tuesdata <- tidytuesdayR::tt_load('2022-02-01')

#Read in the data manually
#breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
#trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
#breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')

# Separate three dataset
breed_traits <- tuesdata$breed_traits
trait_description <- tuesdata$trait_description
breed_rank <- tuesdata$breed_rank
rm(tuesdata)
```

